# This workflow will do a clean install of node dependencies, build the source code and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Install, build, run static code analysis and unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install [wonka-ui]
      run: npm ci
    - name: npm run build [wonka-ui]
      run: npm run build
    - name: Linting [wonka-ui]
      run: npm run lint
    - name: Run unit tests [wonka-ui]
      run: npm run test -- --browsers=ChromeHeadless --watch=false --codeCoverage
    - name: npm install [demo-app]
      working-directory: ./project/application
      run: npm ci
    - name: npm run build [demo-app]
      working-directory: ./project/application
      run: npm run build
    - name: Linting [demo-app]
      working-directory: ./project/application
      run: npm run lint
    - name: Run unit tests [demo-app]
      working-directory: ./project/application
      run: npm run test -- --browsers=ChromeHeadless --watch=false --codeCoverage
